import { getUserUuid } from "@/services/user";
import { getUserCredits, decreaseCredits, CreditsTransType } from "@/services/credit";
import { respData, respErr } from "@/lib/resp";
import PDFDocument from "pdfkit";
import { getFirstPaidOrderByUserUuid } from "@/models/order";

const PDF_COST = 10; // Cost in credits to download PDF

async function generatePaymentGuidePDF(): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: "A4",
      margins: { top: 50, bottom: 50, left: 50, right: 50 },
    });

    const buffers: Buffer[] = [];
    doc.on("data", buffers.push.bind(buffers));
    doc.on("end", () => {
      const pdfBuffer = Buffer.concat(buffers);
      resolve(pdfBuffer);
    });
    doc.on("error", reject);

    // Title
    doc.fontSize(24).text("How to Set Up Alipay and WeChat Pay", { align: "center" });
    doc.moveDown();

    // Introduction
    doc.fontSize(14).text("Introduction", { underline: true });
    doc.fontSize(12).text(
      "Alipay and WeChat Pay are the two most popular mobile payment methods in China. This guide will help you set up both payment methods as an international traveler."
    );
    doc.moveDown();

    // Alipay Section
    doc.fontSize(16).text("Setting Up Alipay", { underline: true });
    doc.moveDown(0.5);
    doc.fontSize(12).text("Step 1: Download the Alipay App", { bold: true });
    doc.fontSize(11).text("• Search for 'Alipay' in your app store");
    doc.fontSize(11).text("• Download and install the official Alipay app");
    doc.moveDown(0.5);

    doc.fontSize(12).text("Step 2: Register Your Account", { bold: true });
    doc.fontSize(11).text("• Open the app and tap 'Sign Up'");
    doc.fontSize(11).text("• Enter your mobile phone number (international numbers are supported)");
    doc.fontSize(11).text("• Verify your phone number with the SMS code");
    doc.moveDown(0.5);

    doc.fontSize(12).text("Step 3: Link Your Card", { bold: true });
    doc.fontSize(11).text("• Go to 'Me' > 'Bank Cards'");
    doc.fontSize(11).text("• Tap 'Add Card' and enter your card details");
    doc.fontSize(11).text("• Supported cards: Visa, Mastercard, and some international cards");
    doc.moveDown(0.5);

    doc.fontSize(12).text("Step 4: Verify Your Identity", { bold: true });
    doc.fontSize(11).text("• You may need to upload a photo of your passport");
    doc.fontSize(11).text("• Complete the identity verification process");
    doc.moveDown();

    // WeChat Pay Section
    doc.fontSize(16).text("Setting Up WeChat Pay", { underline: true });
    doc.moveDown(0.5);
    doc.fontSize(12).text("Step 1: Download WeChat", { bold: true });
    doc.fontSize(11).text("• Download WeChat from your app store");
    doc.fontSize(11).text("• Create a WeChat account if you don't have one");
    doc.moveDown(0.5);

    doc.fontSize(12).text("Step 2: Access WeChat Pay", { bold: true });
    doc.fontSize(11).text("• Open WeChat and tap 'Me'");
    doc.fontSize(11).text("• Tap 'Services' > 'Wallet'");
    doc.moveDown(0.5);

    doc.fontSize(12).text("Step 3: Add Your Card", { bold: true });
    doc.fontSize(11).text("• Tap 'Add Card' in the Wallet section");
    doc.fontSize(11).text("• Enter your card information");
    doc.fontSize(11).text("• Verify your identity if prompted");
    doc.moveDown(0.5);

    doc.fontSize(12).text("Step 4: Set Up Payment Password", { bold: true });
    doc.fontSize(11).text("• Create a 6-digit payment password");
    doc.fontSize(11).text("• This password is required for each transaction");
    doc.moveDown();

    // Tips Section
    doc.fontSize(16).text("Important Tips", { underline: true });
    doc.moveDown(0.5);
    doc.fontSize(11).text("• Keep your phone charged - mobile payments require your phone");
    doc.fontSize(11).text("• Have backup payment methods - cash is still accepted in many places");
    doc.fontSize(11).text("• Check transaction limits - some cards have daily spending limits");
    doc.fontSize(11).text("• Keep your payment password secure");
    doc.fontSize(11).text("• Download both apps - some merchants only accept one payment method");
    doc.moveDown();

    // Footer
    doc.fontSize(10).text("Generated by TravelTang - Your Ultimate Guide to Traveling in China", {
      align: "center",
    });

    doc.end();
  });
}

async function generateCityGuidePDF(): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: "A4",
      margins: { top: 50, bottom: 50, left: 50, right: 50 },
    });

    const buffers: Buffer[] = [];
    doc.on("data", buffers.push.bind(buffers));
    doc.on("end", () => {
      const pdfBuffer = Buffer.concat(buffers);
      resolve(pdfBuffer);
    });
    doc.on("error", reject);

    // Title
    doc.fontSize(24).text("China City Travel Guides", { align: "center" });
    doc.moveDown();

    // Introduction
    doc.fontSize(14).text("Introduction", { underline: true });
    doc.fontSize(12).text(
      "This comprehensive guide covers major Chinese cities with information about attractions, food, transportation, and travel tips."
    );
    doc.moveDown();

    // Beijing Section
    doc.fontSize(16).text("Beijing - The Capital City", { underline: true });
    doc.moveDown(0.5);
    doc.fontSize(12).text("Top Attractions:", { bold: true });
    doc.fontSize(11).text("• Forbidden City - Imperial palace complex");
    doc.fontSize(11).text("• Great Wall of China - Must-see historical wonder");
    doc.fontSize(11).text("• Temple of Heaven - Ancient religious complex");
    doc.fontSize(11).text("• Summer Palace - Beautiful imperial garden");
    doc.moveDown(0.5);

    doc.fontSize(12).text("Food Recommendations:", { bold: true });
    doc.fontSize(11).text("• Peking Duck - Beijing's signature dish");
    doc.fontSize(11).text("• Beijing Noodles (Zhajiangmian)");
    doc.fontSize(11).text("• Hot Pot - Popular dining experience");
    doc.moveDown(0.5);

    doc.fontSize(12).text("Transportation:", { bold: true });
    doc.fontSize(11).text("• Subway system is extensive and easy to use");
    doc.fontSize(11).text("• Taxis and ride-sharing apps available");
    doc.fontSize(11).text("• Download Beijing Subway app for navigation");
    doc.moveDown();

    // Shanghai Section
    doc.fontSize(16).text("Shanghai - The Modern Metropolis", { underline: true });
    doc.moveDown(0.5);
    doc.fontSize(12).text("Top Attractions:", { bold: true });
    doc.fontSize(11).text("• The Bund - Iconic waterfront area");
    doc.fontSize(11).text("• Yu Garden - Traditional Chinese garden");
    doc.fontSize(11).text("• Shanghai Tower - One of the world's tallest buildings");
    doc.fontSize(11).text("• French Concession - Historic neighborhood");
    doc.moveDown(0.5);

    doc.fontSize(12).text("Food Recommendations:", { bold: true });
    doc.fontSize(11).text("• Xiaolongbao (Soup Dumplings)");
    doc.fontSize(11).text("• Shanghai-style noodles");
    doc.fontSize(11).text("• Fresh seafood");
    doc.moveDown(0.5);

    doc.fontSize(12).text("Transportation:", { bold: true });
    doc.fontSize(11).text("• Excellent metro system");
    doc.fontSize(11).text("• Maglev train to Pudong Airport");
    doc.fontSize(11).text("• Buses and taxis widely available");
    doc.moveDown();

    // Xi'an Section
    doc.fontSize(16).text("Xi'an - Ancient Capital", { underline: true });
    doc.moveDown(0.5);
    doc.fontSize(12).text("Top Attractions:", { bold: true });
    doc.fontSize(11).text("• Terracotta Warriors - UNESCO World Heritage");
    doc.fontSize(11).text("• City Wall - Ancient fortification");
    doc.fontSize(11).text("• Big Wild Goose Pagoda");
    doc.moveDown(0.5);

    doc.fontSize(12).text("Food Recommendations:", { bold: true });
    doc.fontSize(11).text("• Roujiamo (Chinese hamburger)");
    doc.fontSize(11).text("• Biangbiang noodles");
    doc.fontSize(11).text("• Yangrou Paomo (Mutton soup)");
    doc.moveDown();

    // General Tips
    doc.fontSize(16).text("General Travel Tips", { underline: true });
    doc.moveDown(0.5);
    doc.fontSize(11).text("• Learn basic Chinese phrases - Hello (你好), Thank you (谢谢)");
    doc.fontSize(11).text("• Download translation apps like Google Translate");
    doc.fontSize(11).text("• Carry your passport at all times");
    doc.fontSize(11).text("• Use VPN apps if you need access to international websites");
    doc.fontSize(11).text("• Respect local customs and traditions");
    doc.fontSize(11).text("• Be cautious with street food - choose busy vendors");
    doc.fontSize(11).text("• Keep emergency contact numbers handy");
    doc.moveDown();

    // Footer
    doc.fontSize(10).text("Generated by TravelTang - Your Ultimate Guide to Traveling in China", {
      align: "center",
    });

    doc.end();
  });
}

export async function POST(req: Request) {
  try {
    const { pdf_type } = await req.json();

    if (!pdf_type || !["payment_guide", "city_guide"].includes(pdf_type)) {
      return respErr("invalid pdf_type");
    }

    const user_uuid = await getUserUuid();
    if (!user_uuid) {
      return respErr("no auth, please sign-in");
    }

    // Check if user has paid order
    const paid_order = await getFirstPaidOrderByUserUuid(user_uuid);
    if (!paid_order) {
      return respErr("please purchase a plan first");
    }

    // Check and deduct credits
    const userCredits = await getUserCredits(user_uuid);
    if (userCredits.left_credits < PDF_COST) {
      return respErr("insufficient credits");
    }

    // Generate PDF
    let pdfBuffer: Buffer;
    let filename: string;

    if (pdf_type === "payment_guide") {
      pdfBuffer = await generatePaymentGuidePDF();
      filename = "TravelTang-Payment-Setup-Guide.pdf";
    } else {
      pdfBuffer = await generateCityGuidePDF();
      filename = "TravelTang-City-Travel-Guides.pdf";
    }

    // Deduct credits
    await decreaseCredits({
      user_uuid,
      trans_type: CreditsTransType.PDFDownload,
      credits: PDF_COST,
    });

    // Return PDF as response
    return new Response(pdfBuffer, {
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="${filename}"`,
        "Content-Length": pdfBuffer.length.toString(),
      },
    });
  } catch (e: any) {
    console.log("download pdf failed: ", e);
    return respErr("download pdf failed: " + e.message);
  }
}

